# Generated by Django 5.1.4 on 2024-12-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentizer',
            name='vector',
            field=models.JSONField(null=True),
        ),
    ]
